### ISSUE TITLE
Set up Environments and Pipeline

### ISSUE THREAD

**Issue by alexmsenger** [MethodenDB-YFU/method-service#31]
- [x] Production DB
- [x] Test DB
- [x] Production Environment
- [ ] Test Environment
- [ ] Jenkins Pipeline

**Comment by alexmsenger** [comment]
## Staging
Staging hosted at `methodendb.berlin-1.alexmsenger.de`. For access please pass your public key. 

`ssh -L 12345:methodendb.berlin-1.alexmsenger.de:8080 berlin-2.alexmsenger.de -p 2222`

Now you can `curl` the endpoints via `curl -L localhost:12345/api/{endpoint}` 

## DBs
Both are hosted at `db.methodendb[-test].berlin-1.alexmsenger.de`. To access via PSQL tunnel into it the same way as for the staging env. 

## Jenkins / CI / CD
Is in the works and expected end of Q1.

**Comment by alexmsenger** [comment]
How about preparation for K8s?

**Comment by mheumann** [comment]
What is K8s?

**Comment by alexmsenger** [comment]
Kubernetes :-)
