### ISSUE TITLE
Versioning the API

### ISSUE THREAD

**Issue by mheumann** [MethodenDB-YFU/method-service#32]
Good practice is to give the api a version. This way it's easier to edit the API without disturbing the running page. So for example "localhost/api/v1/methods"

**Comment by alexmsenger** [comment]
I only somewhat agree. A version definitely has a purpose but usually it's not the endpoint that is versioned (since that should be a permanent Resource Identifier / Location. Rather than putting the version in the URI I'd rather put in in either the header or the event itself.
