### ISSUE TITLE
Filtering for Methods

### ISSUE THREAD

**Issue by alexmsenger** [MethodenDB-YFU/method-service#35]
Methods should only be displayed for a seminar type. (i.e. you can't see methods without specifiying a seminar)

* Figure out what to filter by
* Optionals vs. Required

**Comment by alexmsenger** [comment]
Filtering can be done in the front end for now as it has more protection there. Might be nice for performance improvements later on. 

It seems like a good idea to add **pagination** though.

**Comment by mheumann** [comment]
Frontend has already pagination and the option for filtering (although just the interface but not the function is implemented)

**Comment by alexmsenger** [comment]
That should be fine for now but it won't scale.
